version: "3"
services:
 #H2 database

  h2:
    container_name: h2
    image: oscarfonts/h2
    ports:
      - 8082:8082
    restart: always 


  claim-service:
    container_name: claim-service
    build: Claim-processing-system/target/Claim-processing-system-0.0.1-SNAPSHOT.jar
    network_mode: host
    hostname: localhost
    ports:
     - 8001:8001
    depends_on:
#      - eureka-server
     - h2
    restart: always

  
  
  